
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fshdsmmyuvhqwngkzndm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzaGRzbW15dXZocXduZ2t6bmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODkzMTIsImV4cCI6MjA2Mjk2NTMxMn0.6sgzv8A8x2nMgLOjAf44lXB72L70FxkhUbtrBml7onM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// The createClient function now includes important auth settings
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
